name: Build and Push Docker image to Docker Hub

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # Docker Log in details configured in Github
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        #   registry: https://index.docker.io/v1/
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Folder containing the dockerfile with build and push command  
          context: DockerFileFolder
          push: true
          tags: kwameds/mytestrepo:latest